
# Generated by Django 3.1.2 on 2021-02-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('episodes', models.IntegerField(blank=True, default=12)),
                ('description', models.CharField(blank=True, default='...', max_length=250)),
                ('genres', models.CharField(default='Shonem, comedy, ecchi', max_length=250)),
                ('studios', models.CharField(default='The firm', max_length=250)),
                ('popularity', models.FloatField(blank=True, default=1)),
                ('mean_score', models.FloatField(blank=True, default=1)),
                ('average_score', models.FloatField(blank=True, default=1)),
                ('your_note', models.FloatField(blank=True, default=1, max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
